---
swagger: '2.0'
info:
  title: Enterprise Search API V1
  version: v1
basePath: "/api/v1/ent"
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  authorization_header:
    type: apiKey
    in: header
    name: Authorization
definitions:
  external_id:
    type: string
    minLength: 1
    maxLength: 800
  errors_response:
    type: object
    required:
    - errors
    properties:
      errors:
        type: array
        minItems: 1
        items:
          type: string
  meta_page:
    type: object
    required:
    - page
    properties:
      page:
        type: object
        required:
        - current
        - total_pages
        - total_results
        - size
        properties:
          current:
            type: integer
          total_pages:
            type: integer
          total_results:
            type: integer
          size:
            type: integer
  permissions_array:
    type: array
    maxItems: 1024
    items:
      type: string
      maxLength: 256
  permissions_object:
    type: object
    required:
    - permissions
    properties:
      permissions:
        "$ref": "#/definitions/permissions_array"
  permissions_user:
    type: object
    required:
    - user
    - permissions
    properties:
      user:
        type: string
      permissions:
        "$ref": "#/definitions/permissions_array"
paths:
  "/sources/{content_source_key}/documents/bulk_create":
    post:
      summary: creates documents
      tags:
      - Documents API
      operationId: indexDocuments
      security:
      - authorization_header: []
      x-codegen-request-body-name: documents
      parameters:
      - name: content_source_key
        in: path
        type: string
        required: true
      - name: documents
        in: body
        required: true
        schema:
          type: array
          maxItems: 100
          items:
            type: object
            properties:
              id:
                "$ref": "#/definitions/external_id"
      responses:
        '200':
          description: ok
          schema:
            type: array
            items:
              type: object
              required:
              - id
              - errors
              properties:
                id:
                  "$ref": "#/definitions/external_id"
                errors:
                  type: array
                  items:
                    type: string
        '400':
          description: bad request
          schema:
            "$ref": "#/definitions/errors_response"
        '401':
          description: unauthorized
        '404':
          description: not found
        '413':
          description: payload too large
          schema:
            "$ref": "#/definitions/errors_response"
  "/sources/{content_source_key}/documents/bulk_destroy":
    post:
      summary: destroys documents
      tags:
      - Documents API
      operationId: deleteDocuments
      security:
      - authorization_header: []
      x-codegen-request-body-name: documentIds
      parameters:
      - name: content_source_key
        in: path
        type: string
        required: true
      - name: documents
        in: body
        required: true
        schema:
          type: array
          maxItems: 100
          items:
            "$ref": "#/definitions/external_id"
      responses:
        '200':
          description: ok
          schema:
            type: array
            items:
              type: object
              required:
              - id
              - success
              properties:
                id:
                  "$ref": "#/definitions/external_id"
                success:
                  type: boolean
        '400':
          description: bad request
          schema:
            "$ref": "#/definitions/errors_response"
        '401':
          description: unauthorized
        '404':
          description: not found
        '413':
          description: payload too large
          schema:
            "$ref": "#/definitions/errors_response"
  "/sources/{content_source_key}/permissions":
    get:
      summary: lists permissions
      tags:
      - Permissions API
      operationId: listAllPermissions
      security:
      - authorization_header: []
      parameters:
      - name: content_source_key
        in: path
        type: string
        required: true
      - name: page[current]
        in: query
        type: integer
        required: false
        x-codegen-param-name: currentPage
      - name: page[size]
        in: query
        type: integer
        required: false
        x-codegen-param-name: pageSize
      responses:
        '200':
          description: ok
          schema:
            type: object
            required:
            - meta
            - results
            properties:
              meta:
                "$ref": "#/definitions/meta_page"
              results:
                type: array
                items:
                  "$ref": "#/definitions/permissions_user"
        '401':
          description: unauthorized
        '404':
          description: not found
  "/sources/{content_source_key}/permissions/{user}":
    get:
      summary: shows user permissions
      tags:
      - Permissions API
      operationId: getUserPermissions
      security:
      - authorization_header: []
      parameters:
      - name: content_source_key
        in: path
        type: string
        required: true
      - name: user
        in: path
        type: string
        required: true
      responses:
        '200':
          description: ok
          schema:
            "$ref": "#/definitions/permissions_user"
        '401':
          description: unauthorized
        '404':
          description: not found
    post:
      summary: updates user permissions
      tags:
      - Permissions API
      operationId: updateUserPermissions
      security:
      - authorization_header: []
      x-codegen-request-body-name: permissions
      parameters:
      - name: content_source_key
        in: path
        type: string
        required: true
      - name: user
        in: path
        type: string
        required: true
      - name: permissions
        in: body
        required: true
        schema:
          "$ref": "#/definitions/permissions_object"
      responses:
        '200':
          description: ok
          schema:
            "$ref": "#/definitions/permissions_user"
        '400':
          description: bad request
          schema:
            "$ref": "#/definitions/errors_response"
        '401':
          description: unauthorized
        '404':
          description: not found
  "/sources/{content_source_key}/permissions/{user}/add":
    post:
      summary: adds user permissions
      tags:
      - Permissions API
      operationId: addUserPermissions
      security:
      - authorization_header: []
      x-codegen-request-body-name: permissions
      parameters:
      - name: content_source_key
        in: path
        type: string
        required: true
      - name: user
        in: path
        type: string
        required: true
      - name: permissions
        in: body
        required: true
        schema:
          "$ref": "#/definitions/permissions_object"
      responses:
        '200':
          description: ok
          schema:
            "$ref": "#/definitions/permissions_user"
        '400':
          description: bad request
          schema:
            "$ref": "#/definitions/errors_response"
        '401':
          description: unauthorized
        '404':
          description: not found
  "/sources/{content_source_key}/permissions/{user}/remove":
    post:
      summary: removes user permissions
      tags:
      - Permissions API
      operationId: removeUserPermissions
      security:
      - authorization_header: []
      parameters:
      - name: content_source_key
        in: path
        type: string
        required: true
      - name: user
        in: path
        type: string
        required: true
      - name: permissions
        in: body
        required: true
        schema:
          "$ref": "#/definitions/permissions_object"
      responses:
        '200':
          description: ok
          schema:
            "$ref": "#/definitions/permissions_user"
        '400':
          description: bad request
          schema:
            "$ref": "#/definitions/errors_response"
        '401':
          description: unauthorized
        '404':
          description: not found
